# Note: This file is only for development purpose.
x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

version: '3'

services:
  web:
    image: nginx:1.23-alpine
    container_name: cakephp-app-skeleton-web
    <<: *x-logging
    ports:
      - "8765:80"
    volumes:
      # Nginx config
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Application files
      - ./bin:/var/www/html/bin
      - ./config:/var/www/html/config
      - ./plugins:/var/www/html/plugins
      - ./resources:/var/www/html/resources
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./tests:/var/www/html/tests
      - ./vendor:/var/www/html/vendor
      - ./webroot:/var/www/html/webroot
      - ./server.php:/var/www/html/server.php
      - ./index.php:/var/www/html/index.php
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist
    depends_on:
      - app
    networks:
      - cakephp-app-skeleton

  app:
    build: .
    container_name: cakephp-app-skeleton-app
    <<: *x-logging
    environment:
      DEBUG: "true"
      DATABASE_URL: "mysql://my_app:secret@db/my_app?encoding=utf8&timezone=UTC&cacheMetadata=true"
      CACHE_DEFAULT_URL: "redis://:@cache/?timeout=3600&prefix=cakephp_app_skeleton_"
      CACHE_CAKECORE_URL: "redis://:@cache/?timeout=3600&prefix=cakephp_app_skeleton_core_"
      CACHE_CAKEMODEL_URL: "redis://:@cache/?timeout=3600&prefix=cakephp_app_skeleton_model_"
      CACHE_CAKEROUTES_URL: "redis://:@cache/?timeout=3600&prefix=cakephp_app_skeleton_routes_"
      EMAIL_TRANSPORT_DEFAULT_URL: "smtp://:@mailhog:1025"
    volumes:
      - ./bin:/var/www/html/bin
      - ./config:/var/www/html/config
      - ./plugins:/var/www/html/plugins
      - ./resources:/var/www/html/resources
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./tests:/var/www/html/tests
      - ./vendor:/var/www/html/vendor
      - ./webroot:/var/www/html/webroot
      - ./server.php:/var/www/html/server.php
      - ./index.php:/var/www/html/index.php
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist
    depends_on:
      - db
      - cache
      - mailhog
    networks:
      - cakephp-app-skeleton

  db:
    image: mariadb:10.9
    container_name: cakephp-app-skeleton-db
    <<: *x-logging
    volumes:
      - cakephp-app-skeleton-db:/var/lib/mysql:rw
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=my_app
      - MARIADB_USER=my_app
      - MARIADB_PASSWORD=secret
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-flush-method=fsync --innodb-flush-log-at-trx-commit=0
    ports:
      - "3310:3306"
    networks:
      - cakephp-app-skeleton

  cache:
    image: redis:6.2-alpine
    <<: *x-logging
    container_name: cakephp-app-skeleton-cache
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    ports:
      - "6380:6379"
    networks:
      - cakephp-app-skeleton
    volumes:
      - cakephp-app-skeleton-cache:/data:rw

  ########################
  # Developer tools starts
  ########################
  adminer:
    image: adminer
    container_name: cakephp-app-skeleton-adminer
    <<: *x-logging
    restart: always
    ports:
      - "9001:8080"
    depends_on:
      - db
    networks:
      - cakephp-app-skeleton

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cakephp-app-skeleton-redis-commander
    <<: *x-logging
    restart: always
    environment:
      - REDIS_HOSTS=cache
    ports:
      - "9002:8081"
    depends_on:
      - cache
    networks:
      - cakephp-app-skeleton

  mailhog:
    image: mailhog/mailhog
    container_name: cakephp-app-skeleton-mailhog
    <<: *x-logging
    ports:
      - "1025:1025" # SMTP server
      - "9003:8025" # Web UI
    networks:
      - cakephp-app-skeleton

networks:
  cakephp-app-skeleton:

volumes:
  cakephp-app-skeleton-db:
  cakephp-app-skeleton-cache:
